In [ ]:
pandas

In [ ]:
import pandas as pd
production=pd.Series([30,60,45,25],
index=(["wheat","rice","maize","barley"]))
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#bycrop name label
print(production["rice"])
print(production.loc["rice"])

60
60

In [ ]:
print(production.sum())
print(production.mean())
print(production.median())
print(production.idxmax())

160
40.0
37.5
rice

In [ ]:
increased_production=production*1.10
print(increased_production)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
high_production=production[production>40]
print(high_production)

rice     60
maize    45
dtype: int64

In [ ]:
df=pd.DataFrame({
    "name":["akhil","bobby","charran"],
    "age":[25,30,35],
    "city":["Ny","LA","chicago"]
},index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

      name  age     city
a    akhil   25       Ny
b    bobby   30       LA
c  charran   35  chicago

name    bobby
age        30
city       LA
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

      name  age     city
a    akhil   25       Ny
b    bobby   30       LA
c  charran   35  chicago

      name     city
a    akhil       Ny
c  charran  chicago

a dataframe is atwo dimensional data structure.A table like an excel sheet made of multiple series

In [ ]:

import pandas as pd
data={
    "Farm":["Farm A","Farm C","Farm D","Farm B"],
    "Crop":["Wheat","Rice","maize","barley"],
    "Area_hectares":[10,15,8,12],
    "production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     Farm    Crop  Area_hectares  production_tons
0  Farm A   Wheat             10               30
1  Farm C    Rice             15               60
2  Farm D   maize              8               24
3  Farm B  barley             12               36

In [ ]:
df.head(3)

     Farm   Crop  Area_hectares  production_tons
0  Farm A  Wheat             10               30
1  Farm C   Rice             15               60
2  Farm D  maize              8               24

In [ ]:
df.tail(2)

     Farm    Crop  Area_hectares  production_tons
2  Farm D   maize              8               24
3  Farm B  barley             12               36

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Farm             4 non-null      object
 1   Crop             4 non-null      object
 2   Area_hectares    4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()

       Area_hectares  production_tons
count       4.000000         4.000000
mean       11.250000        37.500000
std         2.986079        15.779734
min         8.000000        24.000000
25%         9.500000        28.500000
50%        11.000000        33.000000
75%        12.750000        42.000000
max        15.000000        60.000000

how to add a new column to the existing one
#yield=production/area

In [ ]:
df["yield_ton_per_hectare"]=df["production_tons"]/df["Area_hectares"]
print(df)

     Farm    Crop  Area_hectares  production_tons  yield_ton_per_hectare
0  Farm A   Wheat             10               30                    3.0
1  Farm C    Rice             15               60                    4.0
2  Farm D   maize              8               24                    3.0
3  Farm B  barley             12               36                    3.0

In [ ]:
print(df.iloc[[1,3]])

     Farm    Crop  Area_hectares  production_tons  yield_ton_per_hectare
1  Farm C    Rice             15               60                    4.0
3  Farm B  barley             12               36                    3.0

In [ ]:
print(df.iloc[[1,3]])

     Farm    Crop  Area_hectares  production_tons  yield_ton_per_hectare
1  Farm C    Rice             15               60                    4.0
3  Farm B  barley             12               36                    3.0

In [ ]:
print(df.iloc[[1,3],[0,1,2]])

     Farm    Crop  Area_hectares
1  Farm C    Rice             15
3  Farm B  barley             12

#filter data
#farms growing wheat

In [ ]:
print(df["Crop"]=="wheat")
print()
wheat_farms=df[df["Crop"]=="wheat"]
print(wheat_farms)

0    False
1    False
2    False
3    False
Name: Crop, dtype: bool

Empty DataFrame
Columns: [Farm, Crop, Area_hectares, production_tons, yield_ton_per_hectare]
Index: []

In [ ]:
high_yield=df[df["yield_ton_per_hectare"]>3]
print(high_yield)

     Farm  Crop  Area_hectares  production_tons  yield_ton_per_hectare
1  Farm C  Rice             15               60                    4.0

In [ ]:
sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

     Farm    Crop  Area_hectares  production_tons  yield_ton_per_hectare
1  Farm C    Rice             15               60                    4.0
3  Farm B  barley             12               36                    3.0
0  Farm A   Wheat             10               30                    3.0
2  Farm D   maize              8               24                    3.0

In [ ]:
avg_yield=df.groupby("Crop")["yield_ton_per_hectare"].sum()
print(avg_yield)

Crop
Rice      4.0
Wheat     3.0
barley    3.0
maize     3.0
Name: yield_ton_per_hectare, dtype: float64